### PR TITLE
Add CNAME file so that github pages works.

### LINKED ISSUE #13: Deploy on github pages
We should be able to deploy this repo as a static site on Github pages so we can have a domain up with all the meetup content.

### PR DESCRIPTION
**Pull request by akumria**
Instructions from:
https://help.github.com/articles/setting-up-your-pages-site-repository/

Part of #13

### CODE REVIEW

**Comment by adamchainz** [comment]
LGTM but will need to merge into `gh-pages` branch rather than `master`, will do the work to serve with Jekyll in #13 before merging this since it's kinda the last step

**Comment by akumria** [comment]
My read of the linked page was:

> For User and Organization Pages sites, the Pages branch is master.

And this is an organisation site ... so it should work.

**Comment by adamchainz** [comment]
It's not an organization pages site, since it's not called djangolondon.github.io: https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages

We should rename it that I think.

Also we don't have Jekyll setup so we'll end up on a domain without any HTML, and thus no content!

**Comment by akumria** [comment]
ahh, I get you now. Is it only @jamespacileo that can do the rename?

**Comment by adamchainz** [comment]
No we all can. I just did. Github helpfully redirects from the old name for some time 👍

**Comment by adamchainz** [comment]
Merged in e9193385e275e291a4b9ea5a178cff36e92c0b1e, thanks

**Pull request closed without merging**
