### PR TITLE
Add 2017-01-10 organizers slides

### PR DESCRIPTION
**Pull request by adamchainz**

### CODE REVIEW

**Comment by akumria** [comment]
Where do I send the invoices for Timeout sponsorship?

Also festicket has not paid for the last couple of months

**Comment by adamchainz** [comment]
See whatsapp

They haven't paid? Okay I'll remove them for today 😢

**Comment by adamchainz** [comment]
Re-added because they replied

**Comment by akumria** [comment]
lgtm.

**Pull request merged**
